 ,--------------------------------------------------------.
| Send and receive messages. USAGE:                        |
| SITE MSG READ - read your messages in inbox              |
| SITE MSG SAVE - save messages from trash to inbox        |
| SITE MSG PURGE - delete messages in trash                |
| SITE MSG TREAD - read messages in trash                  |
| SITE MSG <username> <message>                            |
|                      - send a message to username        |
| SITE MSG { <username> [<username> ...] } <message>       |
|                   - send a message to selected usernames |
| SITE MSG =<group> <message>                              |
|                   - send a message to all users in group |
| SITE MSG * <message> - send a message to everyone        |
 `--------------------------------------------------------'
