name: Sparse mirror
on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

env:
  GIT_USER_NAME: github-actions[bot]
  GIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  get_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch repo from GitLab (skip ARM_MIPS)
        id: fetch
        run: |
          git config --global user.name "${{ env.GIT_USER_NAME }}" && \
          git config --global user.email "${{ env.GIT_USER_EMAIL }}" && \
          git config --global merge.ours.driver true && \
          printf '/*\n!/.gitignore\n!*ARM_MIPS*\n' | git sparse-checkout set --stdin && \
          git remote add upstream https://gitlab.com/silv3rr/io.glftpd.ga.git/ && \
          git fetch upstream
      - name: Checkout and merge
        id: checkout
        run: |
          git checkout main && \
          git merge --allow-unrelated-histories --autostash upstream/main
        if: steps.fetch.outcome == 'success'
      - name: Push
        run: git push origin main
        if: steps.checkout.outcome == 'success'
